deployment:
staging:
branch: main
commands:
- git remote add heroku git@heroku.com:herokuapplicationname.git
- "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
- cd ../../.. && git subtree push --prefix GitHubPath/to/application heroku master